apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: vault-server-headers
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
      X-Forwarded-For: ""
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: vault-redirect-ui
  namespace: vault
spec:
  redirectRegex:
    regex: "^https://vault.example.com/$"
    replacement: "https://vault.example.com/ui/"
    permanent: false
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: vault-tcp
  namespace: vault
spec:
  entryPoints:
    - websecure
  routes:
  - match: HostSNI(`vault.example.com`)
    services:
    - name: vault
      port: 8200
  tls:
    passthrough: true
