
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cysl-ingress
  labels:
    app: cysl-ingress
  annotations:
    kubernetes.io/ingress.class: nginx-public
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
spec:
  rules:
  - http:
      paths:
      # API paths
      - pathType: Prefix
        path: "/api/"
        backend:
          service:
            name: {{ include "helm-chart.fullname" . }}
            port:
              number: 8000
      # Frontend
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: cysl-frontend
            port:
              number: 5000
