apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: cysl-server-headers
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cysl-ingress
  labels:
    app: cysl-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: selfsigned-issuer
    traefik.ingress.kubernetes.io/router.middlewares: cysl-cysl-server-headers@kubernetescrd
    argocd.argoproj.io/sync-options: "Validate=false" 
spec:
  rules:
  - host: api.cysl.space
    http:
      paths:
      # API paths
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: cysl-api
            port:
              number: 8000
  tls:
  - hosts:
    - api.cysl.space
    secretName: cysl-server-tls
