apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cysl-ingress
  labels:
    app: cysl-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
spec:
  rules:
#  - host: {{ .Values.loadBalancer.domainName }}
  - http:
      paths:
      - pathType: Prefix
        path: "/(.*)"
        backend:
          service:
            name: cysl-frontend
            port:
              number: 5000
  
#  - host: "api.{{ .Values.loadBalancer.domainName }}"
  - http:
      paths:
      - pathType: Prefix
        path: "/(.*)"
        backend:
          service:
            name: {{ include "helm-chart.fullname" . }}
            port:
              number: 8000
