{{- if .Values.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-api-prefix
spec:
  stripPrefix:
    prefixes:
      - /api

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cysl-ingress
  labels:
    app: cysl-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-cysl-server-headers@kubernetescrd,{{ .Release.Namespace }}-strip-api-prefix@kubernetescrd
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: selfsigned-issuer
    argocd.argoproj.io/sync-options: "Validate=false"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  rules:
  - host: {{ .Values.global.domainName }}
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: cysl-backend
            port:
              number: {{ .Values.api.port }}
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: cysl-frontend
            port:
              number: {{ .Values.service.port }}
  tls:
  - hosts:
    - {{ .Values.global.domainName }}
    secretName: cysl-frontend-tls
{{- end }}
